### PR TITLE
added Food Nutrition Recommendation System

### LINKED ISSUE #281: 💡[Feature]: Food Nutrition
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It contains nutritional information for a wide range of food items commonly consumed. This dataset aims to support dietary planning, and nutritional analysis.

### Use Case

I want to develop a model for Diet Recommendation System.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by abckhush**
Fixes #281

### CODE REVIEW

**Comment by abckhush** [comment]
@TAHIR0110 @Avdhesh-Varshney Kindly review.

**Comment by abckhush** [comment]
@TAHIR0110 @Avdhesh-Varshney Kindly review only a few days are left.

**Comment by abckhush** [comment]
@TAHIR0110 @Avdhesh-Varshney kindly merge this

**Comment by abckhush** [comment]
@TAHIR0110 @Avdhesh-Varshney @Atharv714 Kindly merge this.

**Comment by TAHIR0110** [comment]
@abckhush merged!!

**Pull request merged**
