### PR TITLE
Create predict_danger.ipynb

### PR DESCRIPTION
**Pull request by Kyouma45**
given a context from the user or data received after converting user speech into text by our advanced NLP models, this model predicts if the user is in danger or not.

### CODE REVIEW

**Comment by Kyouma45** [comment]
@Atharv714 Sir, please review my pull request

**Comment by TAHIR0110** [comment]
@Kyouma45 Could you please create prompts for this? It should succinctly describe a situation where a user might express concern for their safety. Let me know if you need any assistance!

for example:
Prompt: "A person notices a stranger acting suspiciously in a deserted area. They express their worry. Write a message indicating whether they are in danger (Yes/No)."

Example User Input: "I feel uneasy, there's someone lurking around."

Output: "Yes"

**Comment by Kyouma45** [comment]
> @Kyouma45 Could you please create prompts for this? It should succinctly describe a situation where a user might express concern for their safety. Let me know if you need any assistance!
> 
> for example:
> Prompt: "A person notices a stranger acting suspiciously in a deserted area. They express their worry. Write a message indicating whether they are in danger (Yes/No)."
> 
> Example User Input: "I feel uneasy, there's someone lurking around."
> 
> Output: "Yes"

@TAHIR0110 Sir, the model already prints Output (Yes/No) when an user input is provided. Do you need some sample prompts?
I have provided some examples in the end of the notebook explaining how input and output works. Should I attach a screenshot for your reference?
Or should I create some more sample prompts?

**Comment by Kyouma45** [comment]
image
This is the model's output for your response

**Comment by TAHIR0110** [comment]
@Kyouma45 merged!

**Comment by Kyouma45** [comment]
@TAHIR0110 sir, please add gssoc and level2 labels to this PR.
Thank you.

**Comment by Kyouma45** [comment]
@TAHIR0110 Please can you add gssoc label and level 2 label as mentioned in issue #3  ? I apologize for asking for it numerous times but the Program Manager posted this,
"We are in the final stage of leaderboard updates.

I noticed few things PA's not mentioned lables on PR.
like gssoc, level1, level2, level3

gssoc24,GSSoC'24, gssoc

These are the labels.

with level1,level2, level3

recommended to use gssoc. Make sure this is assigned to issues and PR as well."

**Comment by Kyouma45** [comment]
@Atharv714 @TAHIR0110 Sir, please add required labels to the pull request

**Pull request merged**
