### PR TITLE
Added Breast Cancer Detection: #176

### LINKED ISSUE #176: Breast Cancer Detection:
**Is your feature request related to a problem? Please describe.**
This project helps us to Detect  Breast Cancer using machine learning with python.

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

### PR DESCRIPTION
**Pull request by Anshika14528**
Added Breast Cancer Detection model which helps to detect if a person has breast cancer or not. The goal of this project is to build an ML model that can accurately classify whether a tumor is benign or malignant based on various features such as texture, perimeter, and compactness.

closes #176

### CODE REVIEW

**Comment by Anshika14528** [comment]
@TAHIR0110 sir, please review it

**Comment by Anshika14528** [comment]
@TAHIR0110 sir, please review it

**Comment by Anshika14528** [comment]
@TAHIR0110 sir, please review and merge it.

**Comment by Anshika14528** [comment]
@Avdhesh-Varshney sir, please review it.

**Comment by Anshika14528** [comment]
@Avdhesh-Varshney sir , please review and merge it please.

**Comment by Atharv714** [comment]
Merged !!

**Pull request merged**
