### PR TITLE
Added Cervical Cancer Classification

### LINKED ISSUE #275: 💡[Feature]: Cervical Cancer Classification
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The jupyter notebook helps in classification of cervical cancer. Cervical cancer develops in a woman's cervix (the entrance to the uterus from the vagina). Almost all cervical cancer cases (99%) are linked to infection with high-risk human papillomaviruses (HPV), an extremely common virus transmitted through sexual contact.

### Use Case
The Logistic Regression model and Support Vector Classifer model performed have well with an accuracy score of 99.4%

### Benefits

There are many reasons why a cancer can go misdiagnosed, these include:

- The symptoms, especially in the early stages being mistaken for some other type of less serious illness.
- The actual test adminstered by a healthcare professional may give the wrong diagnosis

It is clearly important and evident that a correct diagnosis and early treatment is the best possible way to ensure that a patient has a high chance of surviving.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by navyabijoy**
This project aims to classify cervical cancer risk using machine learning algorithms. The dataset contains various features related to patients' demographics and medical records. We implemented and evaluated two models: Logistic Regression and Support Vector Classifier (SVC). Both models performed equally well, achieving an accuracy score of 99.4%.

## Fixes #275

### CODE REVIEW

**Comment by navyabijoy** [comment]
Hello @TAHIR0110 @Avdhesh-Varshney @Atharv714 sir, 

I have added the implementation for the https://github.com/TAHIR0110/ThereForYou/issues/279 issue please review this PR. Thank you!

**Comment by navyabijoy** [comment]
hello @TAHIR0110 sir,

Could you please review and merge the pr?

Thank You.

**Comment by TAHIR0110** [comment]
@navyabijoy merged, good work!

**Comment by navyabijoy** [comment]
hi @TAHIR0110,

Thank you for reviewing the PR. You have mentioned that it is merged, but for me it still shows that the **PR is open**. Please correct me if I am wrong, and if it is indeed open, then please do merge it.

Thank you so much.

**Pull request merged**
