### PR TITLE
Sleep stagging classification

### LINKED ISSUE #269: Sleep stagging Classification
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 Implement a feature to classify different sleep stages (NREM and REM sleep) based on polysomnographic data, including EEG, EOG, and EMG signals. This feature would analyze these signals to accurately determine the sleep stages and patterns.

### Use Case

A user wears a compatible sleep monitoring device while they sleep. The device records polysomnographic data, which is then analyzed by the AI assistant, Kai, to classify sleep stages. The user receives a detailed report on their sleep patterns, including time spent in each sleep stage, sleep efficiency, and any detected sleep disturbances.

### Benefits

Improved Sleep Quality: Provides users with detailed insights into their sleep patterns, helping them understand and improve their sleep quality.
Personalized Recommendations: Offers tailored advice on improving sleep hygiene based on detected sleep patterns and disturbances.
Health Monitoring: Helps in early detection of sleep disorders, enabling timely medical intervention.
Enhanced User Engagement: Encourages users to engage with the app by providing valuable and personalized sleep data.
Data-Driven Insights: Collects data that can be used for further research and development in the field of sleep medicine and mental health.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by mahek0620**
Closes #269

### CODE REVIEW

**Comment by TAHIR0110** [comment]
@mahek0620 I can't see your trained model anywhere in the file. Moreover, the link to the dataset is also not working.

**Comment by mahek0620** [comment]
@TAHIR0110 dataset link has been changed

**Comment by mahek0620** [comment]
@TAHIR0110 can you re-review as soon as possible as PR merged after tomorrow won't be counted

**Comment by mahek0620** [comment]
@TAHIR0110 sir, can you please review this PR as it been almost 2weeks

**Comment by mahek0620** [comment]
@TAHIR0110 sir its been a long time can you please review this

**Comment by TAHIR0110** [comment]
@mahek0620 merged!

**Pull request merged**
