### PR TITLE
Movies and song recommendation system based on facial expressions #143

### PR DESCRIPTION
**Pull request by Pranshu-jais**
Add folder 'Movies and song recommendation system based on facial expressions

### CODE REVIEW

**Review by Avdhesh-Varshney — COMMENTED** [review]
@Pranshu-jais can you share a working video?

**Comment by Pranshu-jais** [comment]
I have added the working video and  the guidelines, how to run this project

**Review by Avdhesh-Varshney — APPROVED** [review]
@Pranshu-jais pr approved 🎉
But properly link your issue with the pr.

**Comment by Pranshu-jais** [comment]
done, I have linked my issue with the pr.  
My issue was #143

**Comment by TAHIR0110** [comment]
merged! @Pranshu-jais

**Pull request merged**
