### PR TITLE
Added Suicide Prevention and Predicting Model along with their Word Analysis 

### PR DESCRIPTION
**Pull request by Soubeer**
Made the model successfully to work faster than traditionals.
Kept the dataset zone clean for users with comments to use their own dataset or the one used to build the model ,as the dataset used is too large to be kept in a repository.
Includes all word analysis for accurate detection of any signs of suicide attempts.

### CODE REVIEW

**Comment by Soubeer** [comment]
@Atharv714 Sir is there a problem with my task?

**Comment by Soubeer** [comment]
@TAHIR0110 @Atharv714 @sanjay-kv Sir, is there a problem with this task? I have not received any update on this. Also there might be a problem with the level assigned to me under GSSOC'24, is it supposed to be level 2 instead of label 2?

**Comment by sanjay-kv** [comment]
Im not sure what exactly happening here, admins usually takes time to merge and reply you back. I hope this task is assigned to you

**Comment by Soubeer** [comment]
yep this task is assigned to me ,with some issues regarding the level of assignment, its just there's no update regarding my PR ,tho I see other PRs getting merged or updated.

**Pull request merged**
