### PR TITLE
Pneumonia Detection using X-Ray Images

### LINKED ISSUE #323: 💡[Feature]: Pneumonia Detection using X-Ray Images
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I need to add "Pneumonia Detection using X-Ray Images" based on Deep Learning Techniques

@TAHIR0110 @Avdhesh-Varshney please assign me this issue under GSSOC'24

### Use Case

Used to detect Pneumonia

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sreevidya-16**
Fixes #323 issue

@Avdhesh-Varshney, view this PR

### CODE REVIEW

**Comment by sreevidya-16** [comment]
Fixes https://github.com/TAHIR0110/ThereForYou/issues/323 issue

@Avdhesh-Varshney, view this PR

**Comment by sreevidya-16** [comment]
Fixes https://github.com/TAHIR0110/ThereForYou/issues/323 issue

@TAHIR0110, @Avdhesh-Varshney  please view this PR

**Comment by sreevidya-16** [comment]
Fixes https://github.com/TAHIR0110/ThereForYou/issues/323 issue

@TAHIR0110, @Avdhesh-Varshney please view this PR

**Comment by sreevidya-16** [comment]
Fixes https://github.com/TAHIR0110/ThereForYou/issues/323 issue

@Avdhesh-Varshney, view this PR

**Comment by TAHIR0110** [comment]
@sreevidya-16 merged!

**Pull request merged**
