### PR TITLE
here is my assigned PR please look into it issue no#73

### PR DESCRIPTION
**Pull request by PRIYANSHU2026**

### CODE REVIEW

**Comment by PRIYANSHU2026** [comment]
Please merge my model

**Comment by PRIYANSHU2026** [comment]
sir look into it

**Comment by TAHIR0110** [comment]
@PRIYANSHU2026 merged!

**Comment by PRIYANSHU2026** [comment]
Sir please award me lvl 3 badge for my waiting and dedication please

**Comment by TAHIR0110** [comment]
@PRIYANSHU2026 it's not how it works dude, but yea I'll still assign this as level2 anyway.

**Pull request merged**
