### PR TITLE
Added HIV prediction using Machine Learning

### LINKED ISSUE #320: 💡[Feature]: HIV disease prediction using Machine learning
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Kaggle dataset : https://www.kaggle.com/datasets/ishigamisenku10/hiv-prediction

(The following dataset gives information about the person suffering from HIV. This dataset is taken from a hospital. Most of the people gave similar information about their past experiences. Based on those experiences, features have been created.)

The project aims to classify whether the person has the likeliness to suffer from HIV (human immuno-deficiency virus) or not based on various input features in the data using ML models

as a solution i will do a complete data analysis ,EDA , feature engineering and take input on Streamlit application to produce the output.

### Use Case

Early Diagnosis: Machine learning algorithms can analyze medical data to detect early signs of HIV, enabling prompt treatment and better management of the disease.
Resource Allocation: Predictive models can help health organizations identify high-risk populations, optimizing resource distribution and targeted interventions.

### Benefits

Improved Accuracy: Machine learning enhances diagnostic accuracy by identifying subtle patterns in complex datasets that may be overlooked by traditional methods.
Personalized Treatment: By predicting individual responses to different treatment options, machine learning facilitates personalized healthcare, improving patient outcomes and quality of life.

### Add ScreenShots

none

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RajKhanke**
Resolves #320 

This project aims to develop a web application for predicting HIV disease status using a machine learning model. The application leverages the powerful XGBoost algorithm, which has been pre-trained to analyze a variety of health-related and behavioral inputs to determine the likelihood of an individual being HIV positive. The inputs include factors such as age, marital status, history of sexually transmitted diseases (STDs), educational background, HIV testing history, AIDS education, places of seeking sex partners, sexual orientation, drug-taking habits, and awareness before marriage.

The application is built using Streamlit, a popular framework for creating interactive web applications in Python. The user interface is designed to be both functional and visually appealing, featuring stylish fonts, custom CSS for enhanced aesthetics, and relevant images to provide an engaging experience. Users can input their data through sliders and select boxes, ensuring an intuitive and user-friendly interaction.

One of the standout features of the application is the dynamic and responsive design. The app includes a background image related to HIV/AIDS awareness, adding context and visual depth. Additionally, a moving HIV ribbon image is positioned in the corner, symbolizing the cause and drawing attention to the importance of awareness and education. The input and output sections are enclosed in stylish containers with shadows and rounded borders, enhancing readability and focus.

The model's prediction process involves label encoding categorical variables to convert them into numerical format suitable for the model. Upon clicking the 'Predict' button, the app processes the input data, applies the XGBoost model, and displays the prediction result. If the model predicts a positive HIV status, a highlighted error message is shown; otherwise, a success message indicates a negative result.

This project not only demonstrates the practical application of machine learning in healthcare but also highlights the importance of accessible tools for early detection and awareness. By providing a seamless and informative user experience, the application aims to contribute to the ongoing efforts in HIV prevention and education. The integration of relevant imagery and user-friendly design principles ensures that the tool is not only functional but also engaging and supportive of the overall mission to combat HIV/AIDS.

Algorithms used :
XGBOOST , Random Forest , Logistic Regression , Gradient Boosting Machine

(also performed entire data analysis ,EDA ,feature engineering , model comparison and evaluation)

deployed with the help of Streamlit application  as follows :

https://github.com/user-attachments/assets/3226ec52-71b5-47b5-8da3-bb3be00bd38d

### CODE REVIEW

**Comment by RajKhanke** [comment]
@Avdhesh-Varshney @TAHIR0110 please merge this pr along with the level and label of gssoc'24. it will resolve the issue no #320

**Comment by RajKhanke** [comment]
please also look towards my other pr of maternal health risk prediction

**Comment by RajKhanke** [comment]
@Avdhesh-Varshney  ?

**Comment by TAHIR0110** [comment]
@RajKhanke merged!

**Pull request merged**
