### PR TITLE
Added Diseases_Prediction

### LINKED ISSUE #78: Develop an AI-Driven Diagnostic System
Develop an AI-driven diagnostic system to analyze medical data and provide accurate, real-time assessments. The task involves creating algorithms to detect patterns, predict diseases, and recommend treatments, enhancing the efficiency and precision of healthcare diagnostics.

I need this before 22 may.

Hence I will assign this as a level 3 label, due to its deadline.

### PR DESCRIPTION
**Pull request by Kyouma45**
Developed a model to predict over 40 diseases based on 130+ symptoms provided by user. Achieving over 97.6% accuracy.
Fixes #78

### CODE REVIEW

**Comment by Kyouma45** [comment]
Sir @TAHIR0110, 
Please review the pull request.

**Comment by Kyouma45** [comment]
@TAHIR0110 
Input consists of 133 different symptoms.
Screenshot from 2024-05-19 10-19-09

Output is one of the 40 Diseases.
image

With accuracy over 97.6%.
image

**Comment by Divyanshi-2211** [comment]
@Kyouma45
 May I know do you have the train.csv file and the test.csv file or you wrote the symptoms??

**Comment by Kyouma45** [comment]
> @Kyouma45
>  May I know do you have the train.csv file and the test.csv file or you wrote the symptoms??

Sir, I have also uploaded train.csv and test.csv

**Comment by TAHIR0110** [comment]
@Kyouma45 great work!! but adding suggestions and prescribing medicines as well would be appreciated, you could use any pre-trained model for this task or could even use dataset and train a model yourself, once you have done this as well please create another PR we would merge it. as this is a level 3 issue.

**Comment by Kyouma45** [comment]
Sir @TAHIR0110, I have integrated the model with LLM to provide prescriptions.
Now it is working better than before.

Example:
image

**Comment by Kyouma45** [comment]
@TAHIR0110 sir, please add gssoc labels to this PR.
Thank you

**Comment by Kyouma45** [comment]
@TAHIR0110 Please can you add gssoc label and level 3 label as mentioned in the issue #78 ? I apologize for asking for it numerous times but the Program Manager posted this,
"We are final stage of leaderboard updates.

I noticed few things PA's not mentioned lables on PR.
like gssoc, level1, level2, level3

gssoc24,GSSoC'24, gssoc

These are the labels.

with level1,level2, level3

recommended to use gssoc. Make sure this is assigned to issues and PR as well."

**Comment by Kyouma45** [comment]
@Atharv714 @TAHIR0110  Sir, please add required labels to the pull request

**Pull request merged**
