### PR TITLE
Streamlit App for Depression Support  Issue no #99

### PR DESCRIPTION
**Pull request by revanth1718**
This pull request aims to integrate an NLP-based chatbot, designed to provide support for users dealing with depression, into a Streamlit application. The chatbot leverages the power of SpaCy for natural language processing and a pre-defined dataset for generating responses. A detailed video presentation demonstrating the features and functionality of the integrated chatbot is attached. The video showcases the user interface, the chatbot's responses, and the overall user experience:

https://github.com/TAHIR0110/ThereForYou/assets/109272714/5567db44-1823-4cb5-987b-c58c2d3cb2a5

I am Participating in GSSOC'24. Please Label this PR as Level 3

### CODE REVIEW

**Comment by TAHIR0110** [comment]
@revanth1718 merged!

**Comment by revanth1718** [comment]
Thank you

**Comment by Devasy23** [comment]
@TAHIR0110 @revanth1718 This code needed to be cleaned before merging it,

this is a dirty commit, as it contains cache files and a virtual python environment, consider having an `.gitignore` file.

**Comment by Devasy23** [comment]
I have made a pr cleaning this thing and added black formatting changes.

#136

**Pull request merged**
