### PR TITLE
Body Fat Prediction

### LINKED ISSUE #267: 💡[Feature]: Body Fat Prediction
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Body Fat Prediction is the process of estimating an individual's body fat percentage using machine learning techniques. Accurate body fat estimation is crucial for assessing health and fitness levels, managing weight, and preventing obesity-related diseases.

### Use Case

Dataset : https://www.kaggle.com/datasets/fedesoriano/body-fat-prediction-dataset

### Benefits

Helps in early detection of obesity-related health issues like diabetes, cardiovascular diseases, and metabolic syndrome.

Provides data to support public health policies aimed at reducing obesity rates and promoting healthy lifestyles.

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Khushi-Pushkar**
Added Body fat prediction
closes #267

### CODE REVIEW

**Comment by Khushi-Pushkar** [comment]
@TAHIR0110 sir please review and merge

**Comment by Khushi-Pushkar** [comment]
@TAHIR0110 @Atharv714 please review and merge

**Comment by Khushi-Pushkar** [comment]
@TAHIR0110 @Atharv714 sir please review and merge

**Comment by TAHIR0110** [comment]
@Khushi-Pushkar merged!

**Pull request merged**
