### PR TITLE
[New Feature]: Automatic Number plate Recognition System for visually impaired

### PR DESCRIPTION
**Pull request by shaziaakhan**
## Feature Request: Automatic Number Plate Recognition System for Visually Impaired

**Problem:** People who are visually impaired struggle to identify vehicles, especially their license plates. This can be a challenge in various situations.

**Solution:** An Automatic Number Plate Recognition (ANPR) system designed specifically for visually impaired users. This system would leverage the power of computer vision libraries to achieve its functionality.

* **Technical Implementation:** The Automatic Number Plate Recognition (ANPR) System in this project utilizes OpenCV, Python EasyOCR, and Imutils.  
    * OpenCV: An open-source library for computer vision tasks, providing image processing and analysis functionalities.
    * Python EasyOCR: A user-friendly library specifically designed for Optical Character Recognition (OCR) tasks, making it easy to extract text from images like license plates.
    * Imutils: A collection of utility functions built on top of OpenCV, simplifying common image processing operations.
*  These libraries will be used to:
    * Capture an image of a vehicle's license plate using a smartphone camera or a smart assistant device with a camera.
    * Detect the presence of a license plate in the captured image.
    * Perform OCR on the detected license plate to read the characters.

### CODE REVIEW

**Comment by shaziaakhan** [comment]
@TAHIR0110 !

**Comment by shaziaakhan** [comment]
@sanjay-kv @TAHIR0110 It has been more than a week since my PR has been reviewed or even merged, kindly do the needful.

**Comment by shaziaakhan** [comment]
This was assigned _**level 2**_ earlier and not level 1

**Comment by TAHIR0110** [comment]
@shaziaakhan merged!

**Pull request merged**
