### PR TITLE
Depression Detection using user tweets

### PR DESCRIPTION
**Pull request by sanskritiagr**
I have trained the model then using user's twitter username, we can scrape his last tweets to detect if he is in depression or not

### CODE REVIEW

**Comment by sanskritiagr** [comment]
This is level 3. Please assign it under GsSoc'24.

**Comment by sanskritiagr** [comment]
I worked a lot hard on this project. It even has twitter web scraper. It is level 2 atleast. Also please merge this, its been a long time.

**Comment by sanskritiagr** [comment]
@Atharv714 @TAHIR0110 please provide feedback or merge this please.

**Comment by TAHIR0110** [comment]
@sanskritiagr merged!

**Comment by TAHIR0110** [comment]
@sanskritiagr don't worry, I have labeled it as level 3.

**Pull request merged**
