### PR TITLE
Depression classification

### PR DESCRIPTION
**Pull request by mahek0620**

### CODE REVIEW

**Comment by mahek0620** [comment]
@TAHIR0110 can you review it

**Comment by mahek0620** [comment]
@TAHIR0110 it's been a week since PR was raised can you please review as soon as possible

**Comment by mahek0620** [comment]
@TAHIR0110 sir, please review and merge it.

**Comment by Atharv714** [comment]
Heyy, could you pls tell the issue number, so that we can verify it, sorry for the delay in response

**Comment by mahek0620** [comment]
> Heyy, could you pls tell the issue number, so that we can verify it, sorry for the delay in response

Closes #212

**Pull request merged**
