### PR TITLE
GSSoC'24: OCR Detection

### LINKED ISSUE #56: GSSoC'24: OCR Detection (Image to Text)
**Is your feature request related to a problem? Please describe.**
A feature which enhances the functionality of the predictions of danger, or suicidal thoughts. When the victim is in danger and is unable to speak at the moment, a text can be displayed to the camera which can predict the outcomes and notify the nearby users accordingly. For suicide predictions, it is helpful in the situation where the victim is writing the death note, so that the camera may get a glimpse of the note, and via the predictions of the model, it can infer the outcomes.

**Describe the solution you'd like**
The sole purpose is to provide functionality for image to text conversion. For visualization, the frame will have the detected text surrounded with bounding boxes with the text detected and the confidence, if the latter surpasses a certain threshold. A pretrained model from `easyocr` will be used along with `cv2`.

**Use Case**
The extracted text can be used with the existing models in the repository that takes text as their primary input for various predictions.

Please assign it to me under GSSoC'24.

### PR DESCRIPTION
**Pull request by SAM-DEV007**
Resolves #56 

The pull request for the OCR Detection resolving the feature enhancement.

# OCR_Detection

The OCR Detection is introduced in order to help the victims in the situation where they can not use other means to communicate or seek help, other than
written communication shown to the camera. Also, it helps in detecting potential self-harm when the victim is in the process of writing the death note, and the 
camera catches a glimpse of it and can use existing models to determine the scale of the threat that uses text as their primary input.

# Usage
**It is to be kept in mind that a window will only be created if there are text detected by the model. For visualizing another image, that window has to be closed in order for the another window to appear.**

- `demo.py` to start the web camera for obtaining frames.
- Ctrl + C to exit from the script.
- If a text is detected, a new window opens with the text detected, annotations and the confidence. The detected text is also printed for convenience.

# Working
`easyocr` package is used to provide image to text detection. `Model_Data` contains the downloaded model to reduce the online dependancy.

- `detect.py` contains the functions that can be imported by other scripts to be executed to perform image to text detection.
- `demo.py` contains a demo code which showcases the functionality.

OpenCV without GUI (`opencv-python-headless`) is used to optimize the script for detection. It is useful in optimizing the detection speed by removing useless processes used for GUI.
Additionally, for web integration, GUI is not needed but the other functionalities remains the same.

`demo.py` also contains an optimization which prevents the execution of the model detection if the frame difference is less, i.e., the frames hasn't changed much. MSE (Mean Squared Error) is used to calculate the difference between the two frame. The model only gets executed, if the error is greater than `20`. This can be modified by changing the value of `ERR_DIFF`.

Multi-processing can be used to get seamless detections without delay.

# Demo
- The image is purely for the demonstration purposes. The red text shows the detected text (the detected text is large so it is cutting from the screen). The bounding boxes, the green text above it and the confidence is for visualization purposes.

Figure_1

- The more the resolution of the camera, the better the results.

### CODE REVIEW

**Comment by SAM-DEV007** [comment]
@TAHIR0110 Please review the pull request, and let me know if changes are required or not.

**Comment by SAM-DEV007** [comment]
@TAHIR0110 Please also add the labels in the PR, the same that is mentioned in the issue.

**Comment by sudiptasarkar011** [comment]
I would like to work on this, can you please assign this to me?

**Comment by TAHIR0110** [comment]
@SAM-DEV007 I have merged it and labelled it as level3 instead of level1.

**Pull request merged**
