### PR TITLE
Added Infant Health Prediction

### PR DESCRIPTION
**Pull request by Khushi-Pushkar**
Added #221 
Perform Univariate and Multivariate analysis and draw conclusions from there.
Explore Correlation Matrix
Check the distribution(skewness) of the columns
Detect Outliers
Detect Class Label Imbalance

@TAHIR0110 @Atharv714 pls review and merge

### CODE REVIEW

**Comment by Khushi-Pushkar** [comment]
please review and merge @Atharv714 @TAHIR0110

**Comment by Khushi-Pushkar** [comment]
@Avdhesh-Varshney pls review and merge

**Comment by Khushi-Pushkar** [comment]
@Avdhesh-Varshney sir pls review and merge

**Review by Avdhesh-Varshney — APPROVED** [review]

**Comment by Atharv714** [comment]
@Khushi-Pushkar Merged!!

**Pull request merged**
